@LumiLearn.API_HostAddress = https://localhost:7244

POST {{LumiLearn.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "teacher@test.com",
  "password": "Password1!",
  "role": "Teacher"
}

###

POST {{LumiLearn.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "teacher@test.com",
  "password": "Password1!"
}

###

GET {{LumiLearn.API_HostAddress}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmQ5ZDI1Zi1lMWI4LTRiYjgtODNiOS02ZjBkNTgzMzMyMWEiLCJlbWFpbCI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNiZDlkMjVmLWUxYjgtNGJiOC04M2I5LTZmMGQ1ODMzMzIxYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiZXhwIjoxNzg5NDAzMjUyLCJpc3MiOiJMdW1pTGVhcm4uQXBpIiwiYXVkIjoiTHVtaUxlYXJuLkZyb250ZW5kIn0.3T-8iqmpBfIb22Htc-xnpbMGx9wXGqFajO_qxr0lWfQ

###

POST {{LumiLearn.API_HostAddress}}/api/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmQ5ZDI1Zi1lMWI4LTRiYjgtODNiOS02ZjBkNTgzMzMyMWEiLCJlbWFpbCI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNiZDlkMjVmLWUxYjgtNGJiOC04M2I5LTZmMGQ1ODMzMzIxYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiZXhwIjoxNzg5NTczMzM4LCJpc3MiOiJMdW1pTGVhcm4uQXBpIiwiYXVkIjoiTHVtaUxlYXJuLkZyb250ZW5kIn0.M_c2HhlF3YLX8VaOtsV2jXnXpcCe4Bpn9E4ISud5ADk

{
  "name": "Math 200",
  "subject": "Algebra 2",
  "description": "Oh Yeah."
}

###

GET {{LumiLearn.API_HostAddress}}/api/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmQ5ZDI1Zi1lMWI4LTRiYjgtODNiOS02ZjBkNTgzMzMyMWEiLCJlbWFpbCI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNiZDlkMjVmLWUxYjgtNGJiOC04M2I5LTZmMGQ1ODMzMzIxYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiZXhwIjoxNzg5NzUzODI2LCJpc3MiOiJMdW1pTGVhcm4uQXBpIiwiYXVkIjoiTHVtaUxlYXJuLkZyb250ZW5kIn0.qQwFQMRky36qTOZ7jLBeVLJa9Q9JuC1Bxx9L-q1Fpxg

###

POST {{LumiLearn.API_HostAddress}}/api/courses/69694705-4305-4e5c-803e-20623870f24b/enroll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmQ5ZDI1Zi1lMWI4LTRiYjgtODNiOS02ZjBkNTgzMzMyMWEiLCJlbWFpbCI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNiZDlkMjVmLWUxYjgtNGJiOC04M2I5LTZmMGQ1ODMzMzIxYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiZXhwIjoxNzg5NzUzODI2LCJpc3MiOiJMdW1pTGVhcm4uQXBpIiwiYXVkIjoiTHVtaUxlYXJuLkZyb250ZW5kIn0.qQwFQMRky36qTOZ7jLBeVLJa9Q9JuC1Bxx9L-q1Fpxg

###




//student: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2IzM2EzNy00NmVhLTRkNDUtOTY3Yi1jZjE5YjUzNzg4YTEiLCJlbWFpbCI6InN0dWRlbnRAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImZjYjMzYTM3LTQ2ZWEtNGQ0NS05NjdiLWNmMTliNTM3ODhhMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN0dWRlbnRAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiZXhwIjoxNzg5NzUzNjgzLCJpc3MiOiJMdW1pTGVhcm4uQXBpIiwiYXVkIjoiTHVtaUxlYXJuLkZyb250ZW5kIn0.NJhuzJZR4oazcTA-BSBJtf2ouffLt8YVCLhW5EJrcV4
//teacher: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmQ5ZDI1Zi1lMWI4LTRiYjgtODNiOS02ZjBkNTgzMzMyMWEiLCJlbWFpbCI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNiZDlkMjVmLWUxYjgtNGJiOC04M2I5LTZmMGQ1ODMzMzIxYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlYWNoZXJAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiZXhwIjoxNzg5NzUzODI2LCJpc3MiOiJMdW1pTGVhcm4uQXBpIiwiYXVkIjoiTHVtaUxlYXJuLkZyb250ZW5kIn0.qQwFQMRky36qTOZ7jLBeVLJa9Q9JuC1Bxx9L-q1Fpxg
//comp sci id: 964096ae-a7aa-4c3e-afda-854338a07bca
//math id: 69694705-4305-4e5c-803e-20623870f24b
//sociology id: 6fa396e4-e0a7-466d-b036-bc574c985ab1



GET {{LumiLearn.API_HostAddress}}/api/courses/available
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2IzM2EzNy00NmVhLTRkNDUtOTY3Yi1jZjE5YjUzNzg4YTEiLCJlbWFpbCI6InN0dWRlbnRAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImZjYjMzYTM3LTQ2ZWEtNGQ0NS05NjdiLWNmMTliNTM3ODhhMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN0dWRlbnRAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiZXhwIjoxNzg5ODMzMzY0LCJpc3MiOiJMdW1pTGVhcm4uQXBpIiwiYXVkIjoiTHVtaUxlYXJuLkZyb250ZW5kIn0.YcvsnwTR0ALecWtV6wjZvQ0kWh2sx7iVUq2Th5ZdH7o

###
